"""add batch id to bank transactions

Revision ID: 724f8024c307
Revises: db65030c23bb
Create Date: 2024-04-13 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '724f8024c307'
down_revision: Union[str, None] = 'db65030c23bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create bank_statement_batches table first
    op.create_table(
        'bank_statement_batches',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('account_id', sa.BigInteger(), nullable=False),
        sa.Column('batch_reference', sa.String(50), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('number_of_transactions', sa.Integer(), nullable=False),
        sa.Column('total_batch_amount', sa.Float(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('created_by', sa.BigInteger(), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['bank_details.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_statement_batches_id', 'bank_statement_batches', ['id'])
    op.create_index('ix_bank_statement_batches_batch_reference', 'bank_statement_batches', ['batch_reference'], unique=True)

    # Create a default batch for existing transactions
    connection = op.get_bind()
    connection.execute("""
        INSERT INTO bank_statement_batches (
            account_id, batch_reference, start_date, end_date,
            number_of_transactions, total_batch_amount, created_by, updated_by
        )
        SELECT 
            MIN(account_id),
            'LEGACY_BATCH',
            MIN(payment_date),
            MAX(payment_date),
            COUNT(*),
            SUM(amount),
            MIN(created_by),
            MIN(updated_by)
        FROM bank_transactions
        WHERE EXISTS (SELECT 1 FROM bank_transactions LIMIT 1)
        AND NOT EXISTS (SELECT 1 FROM bank_statement_batches WHERE batch_reference = 'LEGACY_BATCH')
    """)

    # Add batch_id column to bank_transactions
    op.add_column('bank_transactions', sa.Column('batch_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'bank_transactions', 'bank_statement_batches', ['batch_id'], ['id'])

    # Update existing transactions to use the default batch
    connection.execute("""
        UPDATE bank_transactions bt
        SET batch_id = (SELECT id FROM bank_statement_batches WHERE batch_reference = 'LEGACY_BATCH')
        WHERE batch_id IS NULL
    """)

    # Make batch_id non-nullable after updating existing records
    op.alter_column('bank_transactions', 'batch_id',
                    existing_type=sa.BigInteger(),
                    nullable=False)

    # Drop is_reconciled column from bank_transactions
    op.drop_column('bank_transactions', 'is_reconciled')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_ratings')
    op.drop_table('chat_messages')
    op.drop_table('chats')
    op.alter_column('courses', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('courses', 'updated_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('courses', 'deleted_by')
    op.alter_column('payment_transactions', 'payment_method',
               existing_type=mysql.ENUM('mpesa', 'bank', 'card', 'cash', 'other'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=mysql.ENUM('M-Pesa', 'Mixx by Yas', 'Airtel Money', 'Bank', 'Card', 'Cash', 'Other'),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('study_material_categories', 'deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user_devices', 'hardware_info',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_devices', 'security_fingerprints',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop foreign key constraint and batch_id column from bank_transactions
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'batch_id')

    # Drop bank_statement_batches table
    op.drop_index('ix_bank_statement_batches_batch_reference', table_name='bank_statement_batches')
    op.drop_index('ix_bank_statement_batches_id', table_name='bank_statement_batches')
    op.drop_table('bank_statement_batches')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_devices', 'security_fingerprints',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('user_devices', 'hardware_info',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('study_material_categories', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('M-Pesa', 'Mixx by Yas', 'Airtel Money', 'Bank', 'Card', 'Cash', 'Other'),
               nullable=True)
    op.alter_column('payment_transactions', 'payment_method',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('mpesa', 'bank', 'card', 'cash', 'other'),
               existing_nullable=False)
    op.add_column('courses', sa.Column('deleted_by', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.alter_column('courses', 'updated_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('courses', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_table('chats')
    op.drop_table('chat_messages')
    op.drop_table('chat_ratings')
    # ### end Alembic commands ###
